Migrate to Jest and convert some tests to new syntax
arestov/deklarota pull request #41
Opened 2020-09-20 17:38 UTC by andreyivlev-sidekick

2020-09-22 20:02 UTC, arestov requested changes
coul

2020-09-22 20:02 UTC, arestov commented on .eslintrc
> +    "jest": true
could you please instead make `.eslintrc.json` inside `test/__tests__`: 

```
{
  "env": {
    "jest": true
  }
}
```


and use `import {describe, expect, test} from '@jest/globals'` in  `.test.js`

2020-09-23 14:38 UTC, andreyivlev-sidekick commented on .eslintrc
> +    "jest": true
Done

2020-09-24 12:08 UTC, arestov approved these changes

2020-09-24 12:08 UTC, merged